export const QUEST_SOURCES = Object.freeze([
  'https://raw.githubusercontent.com/xGustavvo/discord-api-tracker/refs/heads/main/data/quests-01.json',
  'https://raw.githubusercontent.com/xGustavvo/discord-api-tracker/refs/heads/main/data/quests-02.json',
]);

export const FALLBACK_QUEST_SOURCE =
  'https://raw.githubusercontent.com/xGustavvo/discord-api-tracker/refs/heads/main/quest.json';

export const RESTRICTIONS_SOURCE =
  'https://gist.githubusercontent.com/xGustavvo/3d08b7369eb34b50834815fd43176cae/raw';

export const QUEST_CDN = 'https://cdn.discordapp.com/quests';

export const EXCLUDED_QUEST_IDS = new Set([
  '1193992107035983872',
  '1417206015245418566',
  '1223393873447878656',
  '1276640451235156082',
  '1483951358322147380',
  '1519474065293967471',
  '1537905653681487924',
]);

// ISO country/territory names also provide a complete fallback for browsers
// without Intl.DisplayNames. UK is an accepted alias of GB; XK is Kosovo.
const REGION_LABELS = Object.freeze({
  AD: ["安道爾", "Andorra"],
  AE: ["阿拉伯聯合大公國", "United Arab Emirates"],
  AF: ["阿富汗", "Afghanistan"],
  AG: ["安地卡及巴布達", "Antigua & Barbuda"],
  AI: ["安奎拉", "Anguilla"],
  AL: ["阿爾巴尼亞", "Albania"],
  AM: ["亞美尼亞", "Armenia"],
  AO: ["安哥拉", "Angola"],
  AQ: ["南極洲", "Antarctica"],
  AR: ["阿根廷", "Argentina"],
  AS: ["美屬薩摩亞", "American Samoa"],
  AT: ["奧地利", "Austria"],
  AU: ["澳洲", "Australia"],
  AW: ["荷屬阿魯巴", "Aruba"],
  AX: ["奧蘭群島", "Åland Islands"],
  AZ: ["亞塞拜然", "Azerbaijan"],
  BA: ["波士尼亞與赫塞哥維納", "Bosnia & Herzegovina"],
  BB: ["巴貝多", "Barbados"],
  BD: ["孟加拉", "Bangladesh"],
  BE: ["比利時", "Belgium"],
  BF: ["布吉納法索", "Burkina Faso"],
  BG: ["保加利亞", "Bulgaria"],
  BH: ["巴林", "Bahrain"],
  BI: ["蒲隆地", "Burundi"],
  BJ: ["貝南", "Benin"],
  BL: ["聖巴瑟米", "St. Barthélemy"],
  BM: ["百慕達", "Bermuda"],
  BN: ["汶萊", "Brunei"],
  BO: ["玻利維亞", "Bolivia"],
  BQ: ["荷蘭加勒比區", "Caribbean Netherlands"],
  BR: ["巴西", "Brazil"],
  BS: ["巴哈馬", "Bahamas"],
  BT: ["不丹", "Bhutan"],
  BV: ["布威島", "Bouvet Island"],
  BW: ["波札那", "Botswana"],
  BY: ["白俄羅斯", "Belarus"],
  BZ: ["貝里斯", "Belize"],
  CA: ["加拿大", "Canada"],
  CC: ["科克斯（基靈）群島", "Cocos (Keeling) Islands"],
  CD: ["剛果（金夏沙）", "Congo - Kinshasa"],
  CF: ["中非共和國", "Central African Republic"],
  CG: ["剛果（布拉薩）", "Congo - Brazzaville"],
  CH: ["瑞士", "Switzerland"],
  CI: ["象牙海岸", "Côte d’Ivoire"],
  CK: ["庫克群島", "Cook Islands"],
  CL: ["智利", "Chile"],
  CM: ["喀麥隆", "Cameroon"],
  CN: ["中國", "China"],
  CO: ["哥倫比亞", "Colombia"],
  CR: ["哥斯大黎加", "Costa Rica"],
  CU: ["古巴", "Cuba"],
  CV: ["維德角", "Cape Verde"],
  CW: ["庫拉索", "Curaçao"],
  CX: ["聖誕島", "Christmas Island"],
  CY: ["賽普勒斯", "Cyprus"],
  CZ: ["捷克", "Czechia"],
  DE: ["德國", "Germany"],
  DJ: ["吉布地", "Djibouti"],
  DK: ["丹麥", "Denmark"],
  DM: ["多米尼克", "Dominica"],
  DO: ["多明尼加共和國", "Dominican Republic"],
  DZ: ["阿爾及利亞", "Algeria"],
  EC: ["厄瓜多", "Ecuador"],
  EE: ["愛沙尼亞", "Estonia"],
  EG: ["埃及", "Egypt"],
  EH: ["西撒哈拉", "Western Sahara"],
  ER: ["厄利垂亞", "Eritrea"],
  ES: ["西班牙", "Spain"],
  ET: ["衣索比亞", "Ethiopia"],
  FI: ["芬蘭", "Finland"],
  FJ: ["斐濟", "Fiji"],
  FK: ["福克蘭群島", "Falkland Islands"],
  FM: ["密克羅尼西亞", "Micronesia"],
  FO: ["法羅群島", "Faroe Islands"],
  FR: ["法國", "France"],
  GA: ["加彭", "Gabon"],
  GB: ["英國", "United Kingdom"],
  GD: ["格瑞那達", "Grenada"],
  GE: ["喬治亞", "Georgia"],
  GF: ["法屬圭亞那", "French Guiana"],
  GG: ["根息", "Guernsey"],
  GH: ["迦納", "Ghana"],
  GI: ["直布羅陀", "Gibraltar"],
  GL: ["格陵蘭", "Greenland"],
  GM: ["甘比亞", "Gambia"],
  GN: ["幾內亞", "Guinea"],
  GP: ["瓜地洛普", "Guadeloupe"],
  GQ: ["赤道幾內亞", "Equatorial Guinea"],
  GR: ["希臘", "Greece"],
  GS: ["南喬治亞與南三明治群島", "South Georgia & South Sandwich Islands"],
  GT: ["瓜地馬拉", "Guatemala"],
  GU: ["關島", "Guam"],
  GW: ["幾內亞比索", "Guinea-Bissau"],
  GY: ["蓋亞那", "Guyana"],
  HK: ["中國香港特別行政區", "Hong Kong SAR China"],
  HM: ["赫德島及麥唐納群島", "Heard & McDonald Islands"],
  HN: ["宏都拉斯", "Honduras"],
  HR: ["克羅埃西亞", "Croatia"],
  HT: ["海地", "Haiti"],
  HU: ["匈牙利", "Hungary"],
  ID: ["印尼", "Indonesia"],
  IE: ["愛爾蘭", "Ireland"],
  IL: ["以色列", "Israel"],
  IM: ["曼島", "Isle of Man"],
  IN: ["印度", "India"],
  IO: ["英屬印度洋領地", "British Indian Ocean Territory"],
  IQ: ["伊拉克", "Iraq"],
  IR: ["伊朗", "Iran"],
  IS: ["冰島", "Iceland"],
  IT: ["義大利", "Italy"],
  JE: ["澤西島", "Jersey"],
  JM: ["牙買加", "Jamaica"],
  JO: ["約旦", "Jordan"],
  JP: ["日本", "Japan"],
  KE: ["肯亞", "Kenya"],
  KG: ["吉爾吉斯", "Kyrgyzstan"],
  KH: ["柬埔寨", "Cambodia"],
  KI: ["吉里巴斯", "Kiribati"],
  KM: ["葛摩", "Comoros"],
  KN: ["聖克里斯多福及尼維斯", "St. Kitts & Nevis"],
  KP: ["北韓", "North Korea"],
  KR: ["南韓", "South Korea"],
  KW: ["科威特", "Kuwait"],
  KY: ["開曼群島", "Cayman Islands"],
  KZ: ["哈薩克", "Kazakhstan"],
  LA: ["寮國", "Laos"],
  LB: ["黎巴嫩", "Lebanon"],
  LC: ["聖露西亞", "St. Lucia"],
  LI: ["列支敦斯登", "Liechtenstein"],
  LK: ["斯里蘭卡", "Sri Lanka"],
  LR: ["賴比瑞亞", "Liberia"],
  LS: ["賴索托", "Lesotho"],
  LT: ["立陶宛", "Lithuania"],
  LU: ["盧森堡", "Luxembourg"],
  LV: ["拉脫維亞", "Latvia"],
  LY: ["利比亞", "Libya"],
  MA: ["摩洛哥", "Morocco"],
  MC: ["摩納哥", "Monaco"],
  MD: ["摩爾多瓦", "Moldova"],
  ME: ["蒙特內哥羅", "Montenegro"],
  MF: ["法屬聖馬丁", "St. Martin"],
  MG: ["馬達加斯加", "Madagascar"],
  MH: ["馬紹爾群島", "Marshall Islands"],
  MK: ["北馬其頓", "North Macedonia"],
  ML: ["馬利", "Mali"],
  MM: ["緬甸", "Myanmar (Burma)"],
  MN: ["蒙古", "Mongolia"],
  MO: ["中國澳門特別行政區", "Macao SAR China"],
  MP: ["北馬利安納群島", "Northern Mariana Islands"],
  MQ: ["馬丁尼克", "Martinique"],
  MR: ["茅利塔尼亞", "Mauritania"],
  MS: ["蒙哲臘", "Montserrat"],
  MT: ["馬爾他", "Malta"],
  MU: ["模里西斯", "Mauritius"],
  MV: ["馬爾地夫", "Maldives"],
  MW: ["馬拉威", "Malawi"],
  MX: ["墨西哥", "Mexico"],
  MY: ["馬來西亞", "Malaysia"],
  MZ: ["莫三比克", "Mozambique"],
  NA: ["納米比亞", "Namibia"],
  NC: ["新喀里多尼亞", "New Caledonia"],
  NE: ["尼日", "Niger"],
  NF: ["諾福克島", "Norfolk Island"],
  NG: ["奈及利亞", "Nigeria"],
  NI: ["尼加拉瓜", "Nicaragua"],
  NL: ["荷蘭", "Netherlands"],
  NO: ["挪威", "Norway"],
  NP: ["尼泊爾", "Nepal"],
  NR: ["諾魯", "Nauru"],
  NU: ["紐埃島", "Niue"],
  NZ: ["紐西蘭", "New Zealand"],
  OM: ["阿曼", "Oman"],
  PA: ["巴拿馬", "Panama"],
  PE: ["秘魯", "Peru"],
  PF: ["法屬玻里尼西亞", "French Polynesia"],
  PG: ["巴布亞紐幾內亞", "Papua New Guinea"],
  PH: ["菲律賓", "Philippines"],
  PK: ["巴基斯坦", "Pakistan"],
  PL: ["波蘭", "Poland"],
  PM: ["聖皮埃與密克隆群島", "St. Pierre & Miquelon"],
  PN: ["皮特肯群島", "Pitcairn Islands"],
  PR: ["波多黎各", "Puerto Rico"],
  PS: ["巴勒斯坦自治區", "Palestinian Territories"],
  PT: ["葡萄牙", "Portugal"],
  PW: ["帛琉", "Palau"],
  PY: ["巴拉圭", "Paraguay"],
  QA: ["卡達", "Qatar"],
  RE: ["留尼旺", "Réunion"],
  RO: ["羅馬尼亞", "Romania"],
  RS: ["塞爾維亞", "Serbia"],
  RU: ["俄羅斯", "Russia"],
  RW: ["盧安達", "Rwanda"],
  SA: ["沙烏地阿拉伯", "Saudi Arabia"],
  SB: ["索羅門群島", "Solomon Islands"],
  SC: ["塞席爾", "Seychelles"],
  SD: ["蘇丹", "Sudan"],
  SE: ["瑞典", "Sweden"],
  SG: ["新加坡", "Singapore"],
  SH: ["聖赫勒拿島", "St. Helena"],
  SI: ["斯洛維尼亞", "Slovenia"],
  SJ: ["挪威屬斯瓦巴及尖棉", "Svalbard & Jan Mayen"],
  SK: ["斯洛伐克", "Slovakia"],
  SL: ["獅子山", "Sierra Leone"],
  SM: ["聖馬利諾", "San Marino"],
  SN: ["塞內加爾", "Senegal"],
  SO: ["索馬利亞", "Somalia"],
  SR: ["蘇利南", "Suriname"],
  SS: ["南蘇丹", "South Sudan"],
  ST: ["聖多美普林西比", "São Tomé & Príncipe"],
  SV: ["薩爾瓦多", "El Salvador"],
  SX: ["荷屬聖馬丁", "Sint Maarten"],
  SY: ["敘利亞", "Syria"],
  SZ: ["史瓦帝尼", "Eswatini"],
  TC: ["土克斯及開科斯群島", "Turks & Caicos Islands"],
  TD: ["查德", "Chad"],
  TF: ["法屬南部屬地", "French Southern Territories"],
  TG: ["多哥", "Togo"],
  TH: ["泰國", "Thailand"],
  TJ: ["塔吉克", "Tajikistan"],
  TK: ["托克勞群島", "Tokelau"],
  TL: ["東帝汶", "Timor-Leste"],
  TM: ["土庫曼", "Turkmenistan"],
  TN: ["突尼西亞", "Tunisia"],
  TO: ["東加", "Tonga"],
  TR: ["土耳其", "Turkey"],
  TT: ["千里達及托巴哥", "Trinidad & Tobago"],
  TV: ["吐瓦魯", "Tuvalu"],
  TW: ["台灣", "Taiwan"],
  TZ: ["坦尚尼亞", "Tanzania"],
  UA: ["烏克蘭", "Ukraine"],
  UG: ["烏干達", "Uganda"],
  UK: ["英國", "United Kingdom"],
  UM: ["美國本土外小島嶼", "U.S. Outlying Islands"],
  US: ["美國", "United States"],
  UY: ["烏拉圭", "Uruguay"],
  UZ: ["烏茲別克", "Uzbekistan"],
  VA: ["梵蒂岡", "Vatican City"],
  VC: ["聖文森及格瑞那丁", "St. Vincent & Grenadines"],
  VE: ["委內瑞拉", "Venezuela"],
  VG: ["英屬維京群島", "British Virgin Islands"],
  VI: ["美屬維京群島", "U.S. Virgin Islands"],
  VN: ["越南", "Vietnam"],
  VU: ["萬那杜", "Vanuatu"],
  WF: ["瓦利斯群島和富圖那群島", "Wallis & Futuna"],
  WS: ["薩摩亞", "Samoa"],
  XK: ["科索沃", "Kosovo"],
  YE: ["葉門", "Yemen"],
  YT: ["馬約特島", "Mayotte"],
  ZA: ["南非", "South Africa"],
  ZM: ["尚比亞", "Zambia"],
  ZW: ["辛巴威", "Zimbabwe"],
});

export const REGION_NAMES = Object.freeze(Object.fromEntries(
  Object.entries(REGION_LABELS).map(([code, names]) => [code, names[1]]),
));

export const REGION_NAMES_ZH = Object.freeze(Object.fromEntries(
  Object.entries(REGION_LABELS).map(([code, names]) => [code, names[0]]),
));

export const PLATFORM_NAMES = Object.freeze({
  0: 'Any platform',
  1: 'Xbox',
  2: 'PlayStation',
  3: 'Nintendo Switch',
  4: 'PC',
});

export const REWARD_TYPES = Object.freeze({
  1: 'Code Reward',
  2: 'In-game Reward',
  3: 'Avatar Decoration',
  4: 'Discord Orbs',
  5: 'Discord Nitro',
});

export const REWARD_CAT_LABEL = Object.freeze({
  orbs: '⭐ Orbs',
  avatar: '🧩 頭像裝飾',
  ingame: '🎮 遊戲內',
  nitro: '💎 Nitro',
});

export const TASK_CAT_LABEL = Object.freeze({
  play: '🎮 遊玩',
  watch: '📺 觀看',
});

// These records keep the page usable when every public quest source is offline.
// Relative image paths intentionally remain relative to index.html; assetURL()
// preserves document-relative paths instead of treating them as CDN asset names.
export const MOCK_QUESTS = Object.freeze([
  {
    id: 'demo-mhw',
    config: {
      application: {name: 'Monster Hunter Wilds'},
      messages: {
        quest_name: '魔物獵人荒野：公會狩獵任務',
        game_title: 'Monster Hunter Wilds',
        game_publisher: 'CAPCOM',
      },
      assets: {hero: '../image.png', logotype: ''},
      rewards: [{name: '限定武器吊飾與頭像裝飾', type: 3}],
      task_config_v2: {
        tasks: {play: {type: 'play', target: '遊玩 15 分鐘'}},
      },
      starts_at: '2026-07-01T00:00:00Z',
      expires_at: '2026-07-31T23:59:59Z',
    },
  },
  {
    id: 'demo-rushia',
    config: {
      application: {name: 'Hololive Fantasy'},
      messages: {
        quest_name: 'Rushia My Beloved：蝶戀彩蛋任務',
        game_title: 'Hololive Alternative',
        game_publisher: 'Cover Corp',
      },
      assets: {hero: '../d.png', logotype: ''},
      rewards: [{name: '專屬蝶與骷髏頭像框', type: 3}],
      task_config_v2: {
        tasks: {watch: {type: 'watch', target: '觀看直播 10 分鐘'}},
      },
      starts_at: '2026-06-01T00:00:00Z',
      expires_at: '2026-08-01T23:59:59Z',
    },
  },
  {
    id: 'demo-valorant',
    config: {
      application: {name: 'VALORANT'},
      messages: {
        quest_name: '特戰英豪：第三幕挑戰賽',
        game_title: 'VALORANT',
        game_publisher: 'Riot Games',
      },
      assets: {
        hero: 'https://raw.githubusercontent.com/rushiaismywaifu/rushiaismywaifu.github.io/main/image.png',
        logotype: '',
      },
      rewards: [{name: 'Discord Orbs x 500', type: 4, orb_quantity: 500}],
      task_config_v2: {
        tasks: {play: {type: 'play', target: '在對戰中取得 1 次勝利'}},
      },
      starts_at: '2026-07-01T00:00:00Z',
      expires_at: '2026-07-20T23:59:59Z',
    },
  },
]);
